### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by spockoyno** [InfectionAnalytics/COVID19-ProtectiveThreshold#1]
Thank you for the exceptionally valuable piece of research and for making the code available.
It is very useful for my research on covid-19 vaccines optimisation. However, for me and others to build on your code, it would be very helpful if you could please add an open-source licence. 
Thank you in advance.

**Comment by david-s-khoury** [comment]
We have now added a License thank you for your interest. Kind Regards David.
