### ISSUE TITLE
Bug in censored estimation of pooled SD?

### ISSUE THREAD

**Issue by spockoyno** [InfectionAnalytics/COVID19-ProtectiveThreshold#2]
The variable `ListLODtemp` in line 50 of `File1_FitExtractedDataForMeansAndStDev_20210402.R` defines differences of log10 of some values. Then line 52 takes the log10 of  `ListLODtemp` again,  and inputs into the likelihood function. This second log10 seems like an error producing NaNs.

**Comment by david-s-khoury** [comment]
Thank you for raising this issue. It has now been correct. Kind Regards David.
